version: "3.8"
services:
  postgres:
    image: postgres:16.4
    container_name: niaspokr_db
    hostname: niaspokr_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: niaspokr_db
    ports:
      - "32768:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  backend:
#    image: openjdk:21-jdk-slim
#    container_name: niaspokr_backend
#    hostname: niaspokr_backend
#    restart: unless-stopped
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://niaspokr_db:5432/niaspokr_db
#      SPRING_DATASOURCE_USERNAME: rootuser
#      SPRING_DATASOURCE_PASSWORD: pass
#    ports:
#      - "8080:8080"
#    volumes:
#      - backend_data:/app
#  backend-copy:
#    image: openjdk:21-jdk-slim
#    container_name: niaspokr_backend
#    hostname: niaspokr_backend
#    restart: unless-stopped
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://niaspokr_db:5432/niaspokr_db
#      SPRING_DATASOURCE_USERNAME: rootuser
#      SPRING_DATASOURCE_PASSWORD: pass
#    ports:
#      - "8081:8081"
#    volumes:
#      - backend_data:/app

volumes:
  postgres_data:
    driver: local
#  backend_data:
#    driver: local