version: "3.8"
services:
  postgres:
    image: postgres:16.4
    container_name: niaspokr_db
    hostname: niaspokr_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: niaspokr_db
    ports:
      - "32768:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local